window.showcaseCases = [
  {
    id: "timeout_504_mysql",
    title: "504 + 慢 SQL",
    category: "核心场景",
    badge: "推荐",
    route: "performance",
    desc: "Hybrid Router 识别 → 自我纠偏 Policy → MySQL 慢查询发现",
    message: "order-service 下单接口从 10:30 开始大量 504，帮我排查。",
    checks: ["自我纠偏", "慢 SQL", "证据链"],
    animationSteps: [
      {
        type: "router",
        prefix: "[Router]",
        text: "heuristic 识别: 504 + order-service → performance workflow",
        detail: "置信度 0.92 → 跳过 LLM ✓  理由：确定性信号足够，调 LLM 会浪费 ~500 token 且引入幻觉风险",
        status: "ok",
        delay: 100,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "resolve_app",
        detail: "order-service → appId: app-001，代码库: /repos/order-service",
        status: "ok",
        delay: 600,
        toolName: "resolve_app",
        toolInput: { query: "order-service" },
        toolOutput: { appId: "app-001", realName: "order-service", repoPath: "/repos/order-service" },
        riskLevel: "low",
        durationMs: 12,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "query_logs_by_condition",
        detail: "查询 status=504 日志 (window: 10min) → too_many_results: 847 条，超过阈值 200",
        status: "warning",
        delay: 700,
        toolName: "query_logs_by_condition",
        toolInput: { appId: "app-001", conditions: { httpStatus: 504 }, windowMin: 10 },
        toolOutput: { status: "too_many_results", count: 847, message: "结果过宽，建议收窄查询条件" },
        riskLevel: "low",
        durationMs: 134,
      },
      {
        type: "policy",
        prefix: "[Policy]",
        text: "Self-Correction 触发",
        detail: "too_many_results (847 条) → 判断需要收窄 → 加入 timeout 关键词重试",
        status: "warning",
        delay: 500,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "query_logs_by_condition (retry)",
        detail: "收窄条件: keyword=timeout → 12 条 ✓  发现 HikariPool connection timeout after 30000ms",
        status: "ok",
        delay: 700,
        toolName: "query_logs_by_condition (retry)",
        toolInput: { appId: "app-001", conditions: { httpStatus: 504, keyword: "timeout" }, windowMin: 10 },
        toolOutput: {
          status: "ok",
          count: 12,
          logs: [
            { timestamp: "2026-06-01T10:32:14Z", level: "ERROR", message: "HikariPool connection timeout after 30000ms waiting for connection from pool" },
            { timestamp: "2026-06-01T10:32:18Z", level: "ERROR", message: "HikariPool connection timeout after 30000ms waiting for connection from pool" },
          ],
        },
        riskLevel: "low",
        durationMs: 156,
      },
      {
        type: "evidence",
        prefix: "[Evidence]",
        text: "采集: 日志线索",
        detail: "HikariPool connection timeout × 12/10min，关联下游 payment-service 数据库",
        status: "ok",
        delay: 300,
        evidenceSource: "condition_log",
        evidenceSummary: "HikariPool connection timeout × 12/10min",
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "query_mysql_slow_log",
        detail: "查询 payment-service 慢 SQL → 发现 SELECT orders JOIN order_items: P99 4200ms",
        status: "ok",
        delay: 700,
        toolName: "query_mysql_slow_log",
        toolInput: { appId: "app-001", windowMin: 15 },
        toolOutput: {
          status: "ok",
          slowQueries: [
            {
              sql: "SELECT o.*, i.* FROM orders o JOIN order_items i ON o.id = i.order_id WHERE o.user_id = ?",
              p99Ms: 4200,
              avgMs: 3100,
              execCount: 1240,
              dbName: "payment_db",
              recommendation: "order_items.order_id 缺少索引",
            },
          ],
        },
        riskLevel: "low",
        durationMs: 203,
      },
      {
        type: "evidence",
        prefix: "[Evidence]",
        text: "采集: 慢 SQL",
        detail: "P99 4200ms，avg 3100ms，执行 1240 次/10min；order_items.order_id 缺少索引",
        status: "ok",
        delay: 300,
        evidenceSource: "slow_query",
        evidenceSummary: "慢 SQL P99 4200ms · order_items 缺少索引",
      },
      {
        type: "report",
        prefix: "[Report]",
        text: "生成诊断报告",
        detail: "综合 2 条证据 → 根因: DB 连接池耗尽 | 置信度 high (0.85)",
        status: "ok",
        delay: 800,
        isReport: true,
      },
    ],
    run: {
      route: "performance",
      problemType: "504_timeout",
      router: { source: "heuristic", confidence: "0.92" },
      toolCount: 4,
      llmCalls: 0,
      evidenceCount: 2,
    },
    report: {
      problemAnalysis:
        "order-service 下单接口 10:30 起出现大量 504。Hybrid Router 判断为性能类故障（heuristic 置信度 0.92），触发 performance workflow。初次日志查询返回 847 条过宽结果，Self-Correction Policy 自动收窄关键词，命中 HikariPool connection timeout 线索，进而发现 MySQL 慢查询根因。",
      rootCause:
        "payment-service 数据库连接池（HikariPool）耗尽。根因是 SELECT orders JOIN order_items 查询缺少索引，P99 达到 4200ms，大量查询占用连接不释放，导致连接池饱和，order-service 调用持续超时 504。",
      evidence: [
        "HikariPool connection timeout after 30000ms × 12 次/10min（条件日志）",
        "SELECT o.*, i.* FROM orders o JOIN order_items i ON o.id = i.order_id WHERE o.user_id = ?，P99 4200ms，avg 3100ms，执行 1240 次/10min（慢 SQL）",
        "Self-Correction 记录：初次查询 847 条过宽，自动加入 timeout 关键词收窄至 12 条",
      ],
      suggestions: [
        "立即: 扩容 payment-service 实例，临时释放连接压力",
        "短期: ALTER TABLE order_items ADD INDEX idx_order_id (order_id)，消除慢 SQL",
        "中期: 提高 HikariPool maximumPoolSize（50 → 100），并评估 DB 承载能力",
        "长期: 配置连接池使用率 > 80% 告警，P99 > 1000ms 触发预警",
      ],
      verification: [
        "观察 order-service 504 错误率降至 < 0.1%",
        "确认 HikariPool active connections 恢复正常水位（< 50）",
        "验证加索引后 SELECT orders JOIN order_items P99 降至 < 100ms",
      ],
      confidence: "high (0.85)",
    },
  },

  {
    id: "trace_500_npe",
    title: "500 + NullPointerException",
    category: "基础诊断",
    route: "trace-diagnosis",
    desc: "按 trace_id 查链路日志，定位代码异常",
    message: "prod 环境 order-service 下单接口从 10:30 开始大量 500，trace_id 是 demo-trace-001，帮我排查。",
    checks: ["trace 日志", "代码定位", "无 LLM router"],
    animationSteps: [
      {
        type: "router",
        prefix: "[Router]",
        text: "heuristic 识别: trace_id 存在 → trace-diagnosis workflow",
        detail: "置信度 0.95 → 跳过 LLM ✓  理由：trace_id 是强确定性信号，无需 LLM 路由，避免额外延迟和 token 消耗",
        status: "ok",
        delay: 100,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "resolve_app",
        detail: "order-service → appId: app-001",
        status: "ok",
        delay: 600,
        toolName: "resolve_app",
        toolInput: { query: "order-service" },
        toolOutput: { appId: "app-001", realName: "order-service", repoPath: "/repos/order-service" },
        riskLevel: "low",
        durationMs: 11,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "query_logs_by_trace_id",
        detail: "trace_id: demo-trace-001 → 23 条日志 ✓  发现 NullPointerException at OrderCheckoutService.java:142",
        status: "ok",
        delay: 700,
        toolName: "query_logs_by_trace_id",
        toolInput: { traceId: "demo-trace-001", appId: "app-001" },
        toolOutput: {
          status: "ok",
          count: 23,
          logs: [
            {
              timestamp: "2026-06-01T10:31:02Z",
              level: "ERROR",
              message: "java.lang.NullPointerException: Cannot invoke method getDiscount() on null object",
              class: "OrderCheckoutService",
              line: 142,
            },
          ],
        },
        riskLevel: "low",
        durationMs: 98,
      },
      {
        type: "evidence",
        prefix: "[Evidence]",
        text: "采集: trace 日志",
        detail: "NullPointerException at OrderCheckoutService.java:142，userProfile 为 null",
        status: "ok",
        delay: 300,
        evidenceSource: "trace_log",
        evidenceSummary: "NPE: OrderCheckoutService.java:142",
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "ask_codebase",
        detail: "查询 OrderCheckoutService:142 上下文 → userProfile.getDiscount() 缺少 null 检查",
        status: "ok",
        delay: 700,
        toolName: "ask_codebase",
        toolInput: { question: "OrderCheckoutService.java line 142 NullPointerException", appId: "app-001" },
        toolOutput: {
          status: "ok",
          answer:
            "第 142 行调用 userProfile.getDiscount()，但 userProfile 在新注册用户首次下单或 profile 服务降级时可能为 null，导致 NPE。",
          codeSnippet:
            "// OrderCheckoutService.java:140\nUserProfile userProfile = userProfileService.getProfile(userId);\n// Line 142 — missing null check:\ndiscount = userProfile.getDiscount(); // ← NPE here",
        },
        riskLevel: "low",
        durationMs: 187,
      },
      {
        type: "evidence",
        prefix: "[Evidence]",
        text: "采集: 代码上下文",
        detail: "OrderCheckoutService:142，userProfile.getDiscount() 缺少 null 检查，新用户首单必现",
        status: "ok",
        delay: 300,
        evidenceSource: "codebase",
        evidenceSummary: "代码 bug: userProfile null check 缺失",
      },
      {
        type: "report",
        prefix: "[Report]",
        text: "生成诊断报告",
        detail: "综合 2 条证据 → 根因: NPE | 置信度 high (0.91)",
        status: "ok",
        delay: 800,
        isReport: true,
      },
    ],
    run: {
      route: "trace-diagnosis",
      problemType: "500_exception",
      router: { source: "heuristic", confidence: "0.95" },
      toolCount: 3,
      llmCalls: 0,
      evidenceCount: 2,
    },
    report: {
      problemAnalysis:
        "order-service 下单接口 500，trace_id: demo-trace-001。trace 日志定位到 OrderCheckoutService.java:142 抛出 NullPointerException，代码库查询确认根因。",
      rootCause:
        "OrderCheckoutService.buildOrder() 第 142 行调用 userProfile.getDiscount() 未做 null 检查。新注册用户首次下单，或 profile 服务降级时 userProfile 为 null，触发 NPE 导致 500。",
      evidence: [
        "trace 日志: java.lang.NullPointerException at OrderCheckoutService.java:142（trace_id: demo-trace-001）",
        "代码上下文: userProfile.getDiscount() 调用前无 null 检查，新用户首单场景必现",
      ],
      suggestions: [
        "立即: if (userProfile != null) { discount = userProfile.getDiscount(); } else { discount = 0; }",
        "短期: userProfileService.getProfile() 降级时返回 default UserProfile 对象而非 null",
        "长期: 统一对外部服务调用做 Optional 包装，从根本上避免 null 传播",
      ],
      verification: [
        "新用户首单测试：不再触发 NPE 500",
        "profile 服务降级测试：下单流程正常完成",
        "线上 500 错误率恢复 < 0.01%",
      ],
      confidence: "high (0.91)",
    },
  },

  {
    id: "high_risk_restart_pending",
    title: "高风险工具 · HITL 审批",
    category: "HITL",
    badge: "互动",
    route: "performance",
    desc: "高风险操作触发人工审批，演示 Pending-Resume 控制流",
    message: "order-service 下单接口从 10:30 开始大量 504，帮我排查。",
    simulationNote: "模拟注入：工具发现 HikariPool 连接池耗尽，系统推荐执行 restart_service，触发高风险 HITL 审批",
    checks: ["high risk", "pending", "approve / reject"],
    animationSteps: [
      {
        type: "router",
        prefix: "[Router]",
        text: "heuristic 识别: 504 → performance workflow",
        detail: "置信度 0.92 → 跳过 LLM ✓  理由：504 是明确的性能类信号，heuristic 足够，省 token 且结果更稳定",
        status: "ok",
        delay: 100,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "resolve_app",
        detail: "order-service → appId: app-001",
        status: "ok",
        delay: 600,
        toolName: "resolve_app",
        toolInput: { query: "order-service" },
        toolOutput: { appId: "app-001", realName: "order-service" },
        riskLevel: "low",
        durationMs: 11,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "query_logs_by_condition",
        detail: "发现 HikariPool connection timeout → 连接池耗尽，建议重启 payment-service",
        status: "ok",
        delay: 700,
        toolName: "query_logs_by_condition",
        toolInput: { appId: "app-001", conditions: { httpStatus: 504, keyword: "timeout" }, windowMin: 10 },
        toolOutput: { status: "ok", count: 12, logs: [{ message: "HikariPool connection timeout after 30000ms" }] },
        riskLevel: "low",
        durationMs: 143,
      },
      {
        type: "evidence",
        prefix: "[Evidence]",
        text: "采集: 日志线索",
        detail: "连接池耗尽，需要重启 payment-service",
        status: "ok",
        delay: 300,
        evidenceSource: "condition_log",
        evidenceSummary: "HikariPool timeout × 12/10min",
      },
      {
        type: "hitl",
        prefix: "[HITL]",
        text: "高风险工具: restart_service → 触发人工审批",
        detail: "risk: high · 风险策略自动触发人工审批 · 操作不可逆，需要人工确认",
        status: "pending",
        delay: 600,
        hitlPause: true,
        toolName: "restart_service",
        hitlDetail: [
          "工具: restart_service",
          "目标: payment-service (app-001)",
          "Risk Level: high",
          "影响: 服务重启，持续约 15-30 秒中断",
        ],
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "restart_service",
        detail: "Approved → 正在重启 payment-service... 服务已恢复 (18340ms)",
        status: "ok",
        delay: 600,
        afterApproval: true,
        toolName: "restart_service",
        toolInput: { appId: "app-001", service: "payment-service", reason: "HikariPool 连接池耗尽" },
        toolOutput: { status: "ok", message: "payment-service restarted successfully", durationMs: 18340 },
        riskLevel: "high",
        durationMs: 18340,
      },
      {
        type: "report",
        prefix: "[Report]",
        text: "生成诊断报告",
        detail: "根因: 连接池耗尽 · 操作: 已执行 · 置信度 high (0.88)",
        status: "ok",
        delay: 800,
        afterApproval: true,
        isReport: true,
      },
      {
        type: "report",
        prefix: "[Report]",
        text: "生成诊断报告（操作已拒绝）",
        detail: "根因已定位，restart_service 被拒绝 · 置信度 medium (0.62)",
        status: "warning",
        delay: 600,
        afterReject: true,
        isReport: true,
        isRejectReport: true,
      },
    ],
    run: {
      route: "performance",
      problemType: "504_timeout",
      router: { source: "heuristic", confidence: "0.92" },
      toolCount: 3,
      llmCalls: 0,
      evidenceCount: 2,
    },
    report: {
      problemAnalysis:
        "order-service 504，日志发现 HikariPool 连接池耗尽。诊断流程中 restart_service（高风险操作）触发 HITL 审批机制，等待人工确认。",
      rootCause: "payment-service 数据库连接池耗尽，需要重启恢复。",
      evidence: [
        "HikariPool connection timeout after 30000ms × 12 次/10min",
        "高风险工具 restart_service 已通过人工审批并执行",
      ],
      suggestions: [
        "审批执行: restart_service payment-service（已完成）",
        "中期: 提高连接池上限并配置水位告警",
      ],
      verification: ["重启后 504 错误率降低", "确认连接池恢复正常水位"],
      confidence: "high (0.88)",
    },
    reportReject: {
      problemAnalysis: "order-service 504，日志发现 HikariPool 连接池耗尽。restart_service 审批被拒绝，本次无法自动恢复。",
      rootCause: "payment-service 数据库连接池耗尽，需手动处理。",
      evidence: ["HikariPool connection timeout after 30000ms × 12 次/10min", "restart_service 操作被人工拒绝"],
      suggestions: ["手动排查并重启 payment-service", "评估是否可以接受服务中断窗口后重新提交审批"],
      verification: ["服务恢复后确认 504 错误率", "检查连接池状态"],
      confidence: "medium (0.62)",
    },
  },

  {
    id: "insufficient_context",
    title: "上下文不足 · 追问",
    category: "路由控制",
    route: "clarification",
    desc: "信息不足时触发 LLM Router，不调工具，生成追问",
    message: "线上接口好像有问题，帮我看看。",
    checks: ["LLM router", "clarification", "不调工具"],
    animationSteps: [
      {
        type: "router",
        prefix: "[Router]",
        text: "heuristic: 置信度低 (0.18)",
        detail: "输入过于模糊，无服务名/错误类型 → 交给 LLM Router",
        status: "warning",
        delay: 100,
      },
      {
        type: "llm",
        prefix: "[LLM]",
        text: "LLM Router 分析",
        detail: "model: standard | budget: 1000 tokens → 判断信息不足，route: clarification，置信度 0.31",
        status: "ok",
        delay: 800,
        llmRole: "router",
        llmTokens: 312,
        evidenceSource: "llm_router",
        evidenceSummary: "LLM Router → route: clarification，conf: 0.31，tokens: 312",
      },
      {
        type: "report",
        prefix: "[Report]",
        text: "生成追问报告（不调用任何工具）",
        detail: "低置信度，输出需要补充的信息列表",
        status: "ok",
        delay: 600,
        isReport: true,
      },
    ],
    run: {
      route: "clarification",
      problemType: "unclear",
      router: { source: "llm", confidence: "0.31" },
      toolCount: 0,
      llmCalls: 1,
      evidenceCount: 0,
    },
    report: {
      problemAnalysis: "输入信息不足，无法确定具体故障场景，LLM Router 判断置信度仅 0.31，触发 clarification workflow。",
      rootCause: "需要补充上下文信息后重新诊断。",
      evidence: ["LLM Router: 信息不足，无法路由，置信度 0.31"],
      suggestions: [
        "请提供: 具体服务名称（如 order-service、payment-service）",
        "请提供: 错误类型（如 500 / 504 / NPE）或 trace_id",
        "请提供: 问题出现的时间窗口",
      ],
      verification: ["补充上述信息后重新提交"],
      confidence: "low (0.31)",
    },
  },

  {
    id: "redaction_sensitive_log",
    title: "敏感信息脱敏",
    category: "安全防护",
    route: "performance",
    desc: "手机号、邮箱、Secret 在进入 LLM / report 前被脱敏",
    message: "order-service 下单接口从 10:30 开始大量 504，帮我排查。",
    simulationNote: "模拟注入：日志中包含手机号、邮箱、secret key，触发 Redaction 脱敏处理",
    checks: ["手机号", "邮箱", "secret redaction"],
    animationSteps: [
      {
        type: "router",
        prefix: "[Router]",
        text: "heuristic 识别: 504 → performance workflow",
        detail: "置信度 0.92",
        status: "ok",
        delay: 100,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "query_logs_by_condition",
        detail: "查询日志 → 发现含敏感信息的日志（手机号、邮箱、secret key）",
        status: "ok",
        delay: 700,
        toolName: "query_logs_by_condition",
        toolInput: { appId: "app-001", conditions: { httpStatus: 504 }, windowMin: 10 },
        toolOutput: {
          status: "ok",
          count: 8,
          logs: [
            { message: "User 13800138001 checkout failed, email: zhang@example.com, order timeout" },
            { message: "payment secret=sk_prod_abc123xyz connection timeout to DB" },
          ],
        },
        riskLevel: "low",
        durationMs: 121,
      },
      {
        type: "security",
        prefix: "[Security]",
        text: "Redaction 处理",
        detail:
          "原始: 13800138001 → [PHONE_REDACTED] · zhang@example.com → [EMAIL_REDACTED] · sk_prod_abc123xyz → [SECRET_REDACTED]",
        status: "ok",
        delay: 400,
        evidenceSource: "security",
        evidenceSummary: "3 项敏感信息已脱敏，安全边界保持",
      },
      {
        type: "evidence",
        prefix: "[Evidence]",
        text: "采集: 脱敏后日志",
        detail: "证据仅保留脱敏版本，原始敏感信息不进入 LLM / report",
        status: "ok",
        delay: 300,
        evidenceSource: "condition_log",
        evidenceSummary: "连接超时 × 8/10min（敏感信息已脱敏）",
      },
      {
        type: "report",
        prefix: "[Report]",
        text: "生成诊断报告",
        detail: "报告不含原始敏感信息，safetyFlags 标记: redacted",
        status: "ok",
        delay: 800,
        isReport: true,
      },
    ],
    run: {
      route: "performance",
      problemType: "504_timeout",
      router: { source: "heuristic", confidence: "0.92" },
      toolCount: 2,
      llmCalls: 0,
      evidenceCount: 2,
    },
    report: {
      problemAnalysis:
        "order-service 出现 504，日志中含敏感信息（手机号、邮箱、secret key）。在进入 EvidenceStore 和 LLM 前，Redaction 层完成脱敏处理，原始信息不暴露在报告或模型调用中。",
      rootCause: "连接超时，根因需进一步分析（敏感信息已脱敏，证据完整性基本保持）。",
      evidence: [
        "连接超时 × 8 次/10min",
        "Redaction: 手机号 → [PHONE_REDACTED]，邮箱 → [EMAIL_REDACTED]，secret → [SECRET_REDACTED]",
      ],
      suggestions: ["检查 DB 连接配置（原始配置请在安全环境查看）", "增加连接池上限和告警"],
      verification: ["确认 504 错误率降低", "检查脱敏日志审计记录"],
      confidence: "medium (0.72)",
      safetyNote: "本报告不含原始敏感信息",
    },
  },

  {
    id: "loop_max_iterations",
    title: "Loop 超限退出",
    category: "Agent Loop",
    route: "performance",
    desc: "查询持续过宽，自我纠偏耗尽最大重试次数，以 max_iterations 终止",
    message: "order-service 下单接口从 10:30 开始大量 504，帮我排查。",
    simulationNote: "模拟注入：每轮查询均返回 too_many_results，触发 max_iterations 退出",
    checks: ["max_iterations", "3 轮重试", "Loop 终止"],
    animationSteps: [
      {
        type: "router",
        prefix: "[Router]",
        text: "heuristic: 504 → performance workflow",
        detail: "置信度 0.92 → 跳过 LLM ✓",
        status: "ok",
        delay: 100,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "resolve_app",
        detail: "order-service → appId: app-001",
        status: "ok",
        delay: 500,
        toolName: "resolve_app",
        riskLevel: "low",
        durationMs: 11,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "query_logs_by_condition (第 1 轮)",
        detail: "query: status=504 → too_many_results: 命中 847 条，超过阈值",
        status: "warning",
        delay: 700,
        toolName: "query_logs_by_condition",
        riskLevel: "low",
        durationMs: 131,
        evidenceSource: "log_round_1",
        evidenceSummary: "第 1 轮: too_many_results (847 条)",
      },
      {
        type: "policy",
        prefix: "[Policy]",
        text: "Self-Correction: 收窄条件重试 (1/2)",
        detail: "suggestedNextQuery → 加入 timeout 关键词",
        status: "warning",
        delay: 400,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "query_logs_by_condition (第 2 轮)",
        detail: "query: status=504 AND timeout → too_many_results: 仍然 847 条",
        status: "warning",
        delay: 700,
        toolName: "query_logs_by_condition",
        riskLevel: "low",
        durationMs: 128,
        evidenceSource: "log_round_2",
        evidenceSummary: "第 2 轮(收窄): too_many_results (847 条)",
      },
      {
        type: "policy",
        prefix: "[Policy]",
        text: "Self-Correction: 再次收窄重试 (2/2)",
        detail: "继续加入 SQL 关键词",
        status: "warning",
        delay: 400,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "query_logs_by_condition (第 3 轮)",
        detail: "query: status=504 AND timeout AND SQL → too_many_results: 依然 847 条",
        status: "warning",
        delay: 700,
        toolName: "query_logs_by_condition",
        riskLevel: "low",
        durationMs: 135,
        evidenceSource: "log_round_3",
        evidenceSummary: "第 3 轮(再收窄): too_many_results (847 条)",
      },
      {
        type: "policy",
        prefix: "[Loop]",
        text: "Agent Loop 终止: reason=max_iterations",
        detail: "已达最大重试次数(2)，强制退出 Loop。共执行 3 轮，查询仍过宽。terminationReason 写入 Trace。",
        status: "warning",
        delay: 500,
        evidenceSource: "loop_policy",
        evidenceSummary: "Loop terminated: max_iterations，3 轮均 too_many_results",
      },
      {
        type: "report",
        prefix: "[Report]",
        text: "生成降级报告",
        detail: "日志证据不完整，仍尝试慢查询 → confidence=medium",
        status: "ok",
        delay: 800,
        isReport: true,
      },
    ],
    run: {
      route: "performance",
      problemType: "504_timeout",
      router: { source: "heuristic", confidence: "0.92" },
      toolCount: 5,
      llmCalls: 0,
      evidenceCount: 4,
    },
    report: {
      problemAnalysis:
        "order-service 504 排障，性能 workflow 执行了 3 轮日志查询，每轮均返回 too_many_results，Self-Correction Policy 耗尽最大重试次数(2)，以 max_iterations 终止 Agent Loop。",
      rootCause:
        "日志平台查询结果持续过宽，无法精确定位异常日志。可能是查询时间窗口过大或平台异常，导致证据链不完整。",
      evidence: [
        "3 轮 query_logs_by_condition 均返回 too_many_results（>200 条）",
        "Agent Loop terminationReason=max_iterations，已达 maxRetries=2",
        "慢查询尝试执行，未获得有效 SQL 线索",
      ],
      suggestions: [
        "缩短查询时间窗口（由 10min 改为 2min）后重试",
        "直接联系日志平台确认是否有数据量异常",
        "尝试增加更精确的关键词（服务方法名、错误码）",
      ],
      verification: ["缩窄时间窗口后重新发起诊断", "确认日志平台查询容量是否正常"],
      confidence: "medium (0.55)",
    },
  },

  {
    id: "loop_tool_error",
    title: "Loop 工具出错退出",
    category: "Agent Loop",
    route: "performance",
    desc: "日志平台超时，Loop 第 1 轮即以 tool_error 终止，不继续重试",
    message: "order-service 下单接口从 10:30 开始大量 504，帮我排查。",
    simulationNote: "模拟注入：日志平台响应超时（delay 4000ms > TOOL_TIMEOUT_MS 3000ms）",
    checks: ["tool_error", "立即终止", "降级报告"],
    animationSteps: [
      {
        type: "router",
        prefix: "[Router]",
        text: "heuristic: 504 → performance workflow",
        detail: "置信度 0.92 → 跳过 LLM ✓",
        status: "ok",
        delay: 100,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "resolve_app",
        detail: "order-service → appId: app-001",
        status: "ok",
        delay: 500,
        toolName: "resolve_app",
        riskLevel: "low",
        durationMs: 11,
      },
      {
        type: "tool",
        prefix: "[Tool]",
        text: "query_logs_by_condition (第 1 轮)",
        detail: "日志平台无响应… 等待 3000ms → timeout",
        status: "error",
        delay: 500,
        toolName: "query_logs_by_condition",
        riskLevel: "low",
        durationMs: 3000,
        evidenceSource: "log_round_1",
        evidenceSummary: "第 1 轮: timeout (3000ms)，日志平台不可用",
      },
      {
        type: "policy",
        prefix: "[Loop]",
        text: "Agent Loop 终止: reason=tool_error",
        detail: "工具调用出错（status=timeout），立即退出 Loop，不继续重试。terminationReason 写入 Trace。",
        status: "error",
        delay: 400,
        evidenceSource: "loop_policy",
        evidenceSummary: "Loop terminated: tool_error，第 1 轮即中止",
      },
      {
        type: "report",
        prefix: "[Report]",
        text: "生成降级报告",
        detail: "工具失败，证据链中断 → confidence=low",
        status: "ok",
        delay: 700,
        isReport: true,
      },
    ],
    run: {
      route: "performance",
      problemType: "504_timeout",
      router: { source: "heuristic", confidence: "0.92" },
      toolCount: 2,
      llmCalls: 0,
      evidenceCount: 2,
    },
    report: {
      problemAnalysis:
        "order-service 504 排障，日志平台在第 1 轮查询时响应超时（> 3000ms），Agent Loop 以 tool_error 立即终止，不进入重试逻辑。",
      rootCause:
        "日志平台不可用，无法获取应用日志证据，根因无法确认。",
      evidence: [
        "query_logs_by_condition status=timeout（第 1 轮，耗时 > 3000ms）",
        "Agent Loop terminationReason=tool_error，立即终止",
      ],
      suggestions: [
        "确认日志平台健康状态（告警 / 运维群）",
        "日志平台恢复后重新发起诊断",
        "临时通过 trace_id 直接查询单条链路",
      ],
      verification: ["日志平台恢复后重跑 eval，确认 tool status 回到 ok"],
      confidence: "low (0.20)",
    },
  },
];
